import { SacredCharacter } from "./types";

export const SACRED_CHARACTERS: SacredCharacter[] = [
  {
    key: "odin",
    name: "Odin",
    originalName: "Óðinn",
    religion: "mythology",
    role: "The Allfather & Wanderer",
    attributes: ["Wisdom", "Sacrifice", "Runes", "Poetry"],
    scriptureRef: { bookKey: "poetic_edda", bookTitle: "The Poetic Edda" },
    summary: "The chief sovereign of the Norse Aesir gods. He is an ecstatic seeker of wisdom who continuously wanders the nine realms, sacrificing his own eye and hanging from Yggdrasil to unlock the cosmic mysteries of writing runes.",
    detailedEthos: "Unlike standard static protectors, Odin is represented as a dynamic, deeply complex seeker. He values wisdom above comfort and rules through intellectual sorcery, strategic foresight, and self-sacrifice. His missing eye is a physical monument to his willingness to pay any price for ultimate cosmic insight.",
    story: "In the Great Epic of the Gallows, Odin sought the secrets of the Runes, which hold the fundamental structure of destiny. He bound himself to the cosmic ash tree Yggdrasil, pierced by his own spear, and hung suspended there for nine wind-cold nights, neither eating nor drinking. At the peak of his agony, peering down into the dark abyss of Nilfheim, he seized the shining Runes of wisdom and screamed. Having won the sacred writing codes for mankind, he fell back, restored by the vital fluid of poetry.",
    interfaithEcho: "Odin's intense, sacrificial quest for wisdom on the tree mirrors other deep scriptural models of absolute physical sacrifice for cosmic illumination, such as Shiva meditating amidst icy fires or Jesus hanging upon the cross to reveal spiritual love.",
    imageUrl: "https://images.unsplash.com/photo-1518156677180-95a2893f3e9f?auto=format&fit=crop&w=600&q=80",
    imageCaption: "A majestic, aged wanderer in a heavy wool cloak carrying a wooden staff through misty trees, representing Odin seeking runic secrets."
  },
  {
    key: "thor",
    name: "Thor",
    originalName: "Þórr",
    religion: "mythology",
    role: "The Thunderous Guardian",
    attributes: ["Strength", "Protection", "Sincerity", "Mjolnir"],
    scriptureRef: { bookKey: "poetic_edda", bookTitle: "The Poetic Edda" },
    summary: "The Norse god of thunder, agriculture, and protection. Standing as the ultimate physical shield of mankind (Midgard), Thor rides a chariot drawn by goats and wields the mountain-shattering hammer, Mjolnir.",
    detailedEthos: "Thor represents physical bravery paired with sincere loyalty. Unlike Odin's complex and secretive nature, Thor is honest, straightforward, and intensely devoted to protecting human farmers and weak creatures from the chaotic giants of frost and fire.",
    story: "In the Lay of Thrymskvida, the giant king Thrym stole Thor's sacred hammer, Mjolnir, demanding the beautiful goddess Freya in marriage as ransom. To recover the weapon without causing a cosmic war, Thor agreed to a clever plan hatched by Loki: he dressed in a bridal veil to impersonate Freya. At the wedding feast, Thor's giant appetite nearly gave him away, but Loki claimed 'Freya' had fasted for eight days in excitement. When the happy giant ordered Mjolnir to be placed in the bride's lap for a holy blessing, Thor grasped the hammer, cast off the veil, and defeated the thieves.",
    interfaithEcho: "As a divine defender of celestial and human borders wielding a thunder weapon, Thor displays a striking physical parallel to Indra in the Hindu Rig Veda or Zeus in Greek lore, displaying humanity's ancient archetype of thunder representing cosmic order defeating chaos.",
    imageUrl: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=600&q=80",
    imageCaption: "Fierce cracks of celestial lightning illuminating dark storm clouds, representing Thor's mountain-shattering hammer Mjolnir."
  },
  {
    key: "freya",
    name: "Freya",
    originalName: "Freyja",
    religion: "mythology",
    role: "Goddess of Love & Magic",
    attributes: ["Fertility", "Seiðr Sorcery", "Independence", "Valor"],
    scriptureRef: { bookKey: "poetic_edda", bookTitle: "The Poetic Edda" },
    summary: "The Vanir goddess of love, sex, beauty, fertility, and gold, who is also a chooser of the slain in battle. She introduced the magical arts of Seiðr to the Aesir gods and rides a chariot pulled by two blue forest cats.",
    detailedEthos: "Freya represents independent agency, beauty, and magical power. She refuses to be treated as a passive prize or commodity by giants. She commands her own heavenly field, Fólkvangr, where she receives half of all warriors who fall in righteous combat, expressing a unique fusion of maternal nurture and warrior courage.",
    story: "When the walls of Asgard were being repaired by a mysterious fortress-builder who demanded Freya as payment, she fiercely rebelled, encouraging the gods to use every strategic means to trick the builder. She wears the magical necklace Brísingamen, which shines like the stars, and possesses a falcon-feathered cloak that grants flight. When she weeps, her tears turn into pure, beautiful red gold, showing her connection to natural abundance and deep sorrow.",
    interfaithEcho: "Freya shares notable traits with other independent feminine sovereign goddesses, such as Durga in Hinduism or Inanna/Ishtar in ancient Mesopotamian scriptures, bridging deep love, mystical wisdom, and formidable protectors of the cosmos.",
    imageUrl: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=600&q=80",
    imageCaption: "A majestic golden royal crown representing Freya's status as goddess of love, beauty, and magic."
  },
  {
    key: "krishna",
    name: "Lord Krishna",
    originalName: "श्रीकृष्ण",
    religion: "hinduism",
    role: "Cosmic Charioteer & Teacher",
    attributes: ["Selfless Duty", "Divine Love", "Playfulness", "Oneness"],
    scriptureRef: { bookKey: "bhagavad_gita", bookTitle: "Bhagavad Gita" },
    summary: "An avatar of Lord Vishnu, Krishna is the supreme teacher of the Bhagavad Gita and the central emblem of Bhakti (devotional love) in Hinduism, guiding Prince Arjuna through ethical warfare with direct philosophical instructions.",
    detailedEthos: "Krishna is the ultimate multi-dimensional divine persona: a playful infant stealing butter, a flute-playing youth calling souls to divine union, and a master strategist. In the Gita, he introduces the three yogas (action, devotion, and knowledge), synthesizing absolute action with deep internal detachment.",
    story: "On the battlefield of Kurukshetra, prince Arjuna collapsed in grief and moral hesitation, refusing to fight his own family members. Krishna, acting as his humble charioteer, compiled the 700 verses of the Gita. To dissolve Arjuna's ego and intellectual pride, Krishna temporarily revealed his Vishwarupa—his supreme, multi-headed cosmic form showing all worlds, stars, and times flowing through his body, showing Arjuna that life and death are expressions of one infinite rhythm.",
    interfaithEcho: "Krishna's call to unconditional surrender in Gita 18.66 ('Abandon all varieties of dharma and surrender unto Me alone; I shall deliver you') echoes Jesus' calls to faith and absolute trust in the Gospels, highlighting divine custody.",
    imageUrl: "https://images.unsplash.com/photo-1590418606746-018840f9cd0f?auto=format&fit=crop&w=600&q=80",
    imageCaption: "A beautiful close-up of a peacock feather, traditionally worn by Lord Krishna as a symbol of divine beauty and Bhakti."
  },
  {
    key: "shiva",
    name: "Lord Shiva",
    originalName: "शिव",
    religion: "hinduism",
    role: "The Great Yogi & Destroyer",
    attributes: ["Asceticism", "Inner Silence", "Cosmic Dance", "Destroyer of Ego"],
    scriptureRef: { bookKey: "upanishads", bookTitle: "Principal Upanishads" },
    summary: "The Auspicious One in the Hindu Trinity, Shiva is the supreme ascetic hermit of Mount Kailash and the cosmic dancer Nataraja, representing the ultimate dissolution of the ego, ignorance, and material illusion.",
    detailedEthos: "Shiva represents absolute calm, deep meditative silence, and the destruction of the old to make way for spiritual rebirth. Resting on ashes with a blue throat from swallowing cosmic poison, he is the savior of the world, representing how a great person absorbs society's bitterness to grant general peace.",
    story: "During the churning of the cosmic ocean (Samudra Manthan), a deadly poison named Halahala emerged, threatening to extinguish all life in the universe. Neither gods nor demons knew how to stop it. Out of absolute compassion, Shiva gathered the poison in his palms and drank it. His consort Parvati clasped his neck to prevent the poison from descending into his stomach, leaving his throat bright blue (Nilakantha), showing how deep compassion requires holding and transforming suffering.",
    interfaithEcho: "Shiva's blue-throated poison sacrifice closely aligns with the theological themes of the suffering servant in Isaiah or Christ's absolute absorption of human sin upon the cross, depicting the divine taking on suffering for planetary salvation.",
    imageUrl: "https://images.unsplash.com/photo-1609137144813-94c632616238?auto=format&fit=crop&w=600&q=80",
    imageCaption: "A majestic rendering of supreme Lord Shiva meditating peacefully by the Ganges, representing introspection, focus, and inner silence."
  },
  {
    key: "rama",
    name: "Lord Rama",
    originalName: "श्रीराम",
    religion: "hinduism",
    role: "The King of Righteous Duty",
    attributes: ["Dharma", "Integrity", "Exile", "Maryada Purushottama"],
    scriptureRef: { bookKey: "ramayana", bookTitle: "Ramayana" },
    summary: "The seventh avatar of Vishnu and king of Ayodhya. Revered as the pinnacle of human righteousness (Maryada Purushottama), Rama sacrifices his crown and endures fourteen years of forest exile to preserve familial honor and defeat Ravana.",
    detailedEthos: "Rama is the embodiment of impeccable ethical duty (Dharma). He shows how a righteous human must act under intense personal, royal, and existential conflicts. He remains perfectly calm, kind, and devoted to truth, never violating his ethical boundaries even when struck by betrayal, loss, and exile.",
    story: "On the eve of his grand coronation, Rama was ordered into 14 years of harsh wilderness exile due to an ancient promise his father King Dasharatha made to queen Kaikeyi. Instead of turning angry or rebelling, Rama accepted the exile with a warm smile, teaching that keeping a father's word is greater than any earthly kingdom. In the forest, when his beloved Sita was snatched by Ravana, he forged alliances with common forest dwellers, eventually marching across a stone bridge over the ocean to defeat the empire of pride.",
    interfaithEcho: "Rama's willing sacrifice of Kingly power out of duty and love for his father mirrors the absolute obedience of Isaac in the Torah and Jesus' total submission in Gethsemane, demonstrating that true kingship begins with voluntary self-denial.",
    imageUrl: "https://images.unsplash.com/photo-1561361513-2d000a50f0db?auto=format&fit=crop&w=600&q=80",
    imageCaption: "An elegant representation of the golden idol of Lord Rama holding his divine bow, representing the path of righteousness and Dharma."
  },
  {
    key: "indra",
    name: "Lord Indra",
    originalName: "इन्द्र",
    religion: "hinduism",
    role: "King of the Celestial Devas",
    attributes: ["Thunderbolt", "Sovereignty", "Rain", "Rig Veda Leader"],
    scriptureRef: { bookKey: "upanishads", bookTitle: "Principal Upanishads" },
    summary: "The ancient Vedic king of the gods, controller of the heavens (Swarga), rain, and storms. He wields the lightning weapon Vajra, forged from the bones of Sage Dadhichi, and leads the celestial beings against dark forces of drought.",
    detailedEthos: "Indra represents the dynamic energy of human vitality, leadership, and the struggle to protect cosmic flow. While he is powerful and battles relentless adversaries, Vedic texts also display his vulnerabilities, reminding humanity that even celestial rulers must remain humble, vigilantly ethical, and aligned with eternal Dharma.",
    story: "The monstrous serpent Vritra stole all the waters of the world, trapping them inside a mountain and casting a dark drought across the earth. To defeat this absolute crisis, Sage Dadhichi selflessly gave his own spine to forge the supreme thunderbolt Vajra. Wielding this weapon of pure spiritual sacrifice and thunder, Indra rode his white elephant Airavata into battle, split Vritra open, and released the rivers of life back to humanity.",
    interfaithEcho: "Indra's triumph over Vritra to release the waters is a direct structural mirror to Thor fighting the Midgard serpent Jormungandr or Archangel Michael casting down the ancient dragon in Revelation, representing the light of cosmic duty reclaiming natural order.",
    imageUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=600&q=80",
    imageCaption: "A majestic storm of lightning and cosmic thunderclouds, representing Lord Indra's celestial thunderbolts, sovereignty, and rain-giving grace."
  },
  {
    key: "shani",
    name: "Lord Shani",
    originalName: "शनिदेव",
    religion: "hinduism",
    role: "The Judge of Karmic Deeds",
    attributes: ["Karma", "Discipline", "Justice", "Patience"],
    scriptureRef: { bookKey: "bhagavad_gita", bookTitle: "Bhagavad Gita" },
    summary: "The Hindu deity representing the planet Saturn, Shani is the lord of absolute justice and retribution. He delivers the fruits of a person's thoughts, speech, and deeds (Karma) without favoritism, encouraging spiritual purification.",
    detailedEthos: "Often misunderstood as a creator of misfortune, Shani is actually the ultimate cosmic tutor. He represents patient discipline, humility, and accountability. He strips away false pride and worldly ego, teaching that suffering is a process of purifying bad karmic debts and achieving wisdom through time.",
    story: "Shani is the son of Surya (the Sun God) and Chhaya (Shadow). When Shani first opened his eyes as a newborn child, his deep gaze was so immense and purifying that it plunged the Sun itself into an eclipse, showing that cosmic justice is completely blind to status and power—even the supreme solar luminary must undergo the period of eclipsing discipline under the law of Karma.",
    interfaithEcho: "Shani's role as a blind arbiter of karmic law and discipline mirrors the Judgements of God in the Abrahamic prophets, where adversity is not a random malice but a structured call to repentance, purification, and spiritual correction.",
    imageUrl: "https://images.unsplash.com/photo-1506318137071-a8e063b4bec0?auto=format&fit=crop&w=600&q=80",
    imageCaption: "The deep cosmic starry universe, representing Lord Shani's strict karmic discipline and cosmic justice."
  },
  {
    key: "john",
    name: "John the Baptist",
    originalName: "Ἰωάννης ὁ βαπτιστής",
    religion: "christianity",
    role: "The Voice in the Wilderness",
    attributes: ["Humility", "Prophecy", "Asceticism", "Preparation"],
    scriptureRef: { bookKey: "bible_nt", bookTitle: "New Testament" },
    summary: "A wild, ascetic prophet in the Judean wilderness who dressed in camel's hair and announced the coming of the Messiah, calling all people to immediate repentance and cleansing through baptism in the River Jordan.",
    detailedEthos: "John represents absolute, uncompromising moral clarity and supreme humility. While he commanded a massive following of devoted disciples, he readily stepped aside, declaring that his entire existence was merely to serve as a voice preparing the path for a greater light.",
    story: "Living off locusts and wild honey, John stood in the rushing waters of the Jordan, pouring water over thousands who confessed their ethical failings. When Yeshu (Jesus) arrived requesting baptism, John hesitated, saying he was not even worthy to untie Jesus' sandals. But he complied, and as he raised Jesus from the water, the heavens parted, showing that John's humble preparation had opened the gateway of global grace.",
    interfaithEcho: "John the Baptist represents the classic archetype of the ascetic forest seer who renounces all family ties and comforts to speak truth to corrupt rulers, mirroring early Vedic forest rishis or the strict ascetic wandering of Mahavira.",
    imageUrl: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=600&q=80",
    imageCaption: "A mystical forest stream flowing quietly through dense foliage and morning mist, representing John the Baptist preparing paths of purification."
  },
  {
    key: "david",
    name: "King David",
    originalName: "דָּוִד",
    religion: "judaism",
    role: "The Psalmist & Shepherd King",
    attributes: ["Faith", "Poetry", "Repentance", "Courage"],
    scriptureRef: { bookKey: "bible_nt", bookTitle: "The Bible" },
    summary: "The young shepherd boy who famously slew the giant warrior Goliath with a single sling-stone and rose to become the greatest king of Israel, composing the beautiful book of Psalms expressing the soul's deep devotion.",
    detailedEthos: "David represents the beautiful dynamic of human faith overcoming physical giants, paired with the humility of immediate repentance. He is not a flawless king, but he is beloved because whenever he fails ethically, he immediately sheds his crown, lies in the dust, and pleads for divine forgiveness with absolute sincerity.",
    story: "When the massive Philistine champion Goliath stepped forward for forty days mocking Israel, no soldier dared fight him. David, a mere youth bringing cheese and bread to his brothers, refuse to surrender to fear. Armored only in his faith in God, he rejected the heavy kingly armor, picked up five smooth stones from the stream, and ran directly toward the giant. With a single, well-aimed strike of his sling, he felled the giant, teaching that spiritual trust is greater than any iron sword.",
    interfaithEcho: "David's courageous battle against an imposing giant using only a simple weapon and pure spiritual faith closely resembles Arjuna facing a massive army in the Mahabharata or Yudhisthira conquering through moral truth.",
    imageUrl: "https://images.unsplash.com/photo-1484557052118-f32bd25b45b5?auto=format&fit=crop&w=600&q=80",
    imageCaption: "A peaceful flock of sheep grazing on green, rolling hills, symbolizing David's life as a shepherd before becoming king."
  },
  {
    key: "yeshu",
    name: "Yeshu (Jesus)",
    originalName: "Yeshua / Ἰησοῦς",
    religion: "christianity",
    role: "Embodiment of Unconditional Love",
    attributes: ["Love (Agape)", "Forgiveness", "Healing", "Sacrifice"],
    scriptureRef: { bookKey: "bible_nt", bookTitle: "New Testament" },
    summary: "Jesus of Nazareth, the central figure of Christianity. He taught the revolutionary Beatitudes, healed the outcast, and offered his life upon the cross, demonstrating radical forgiveness and absolute sacrificial love.",
    detailedEthos: "Yeshu represents a total inversion of human power structures. He rules not by dominating others, but by washing his disciples' feet and giving his own life as a ransom. His message is 'Agape'—unconditional, self-giving love that extends even to our enemies, breaking the ancient human cycles of eye-for-an-eye retaliation.",
    story: "As he was nailed to the Roman cross amidst mockers and soldiers, Jesus did not call down thunder or lightning to destroy his executioners. Instead, looking down with deep compassion, he prayed: 'Father, forgive them, for they know not what they do.' In this ultimate moment, he demonstrated his own teaching that love is only perfect when it is offered to those who hate us.",
    interfaithEcho: "Jesus' radical teaching of loving one's enemies and non-retaliation matches the core Jain philosophy of Ahimsa (absolute non-violence in mind, words, and deeds) and the Buddhist Dhammapada's instruction that hatred is only conquered by love.",
    imageUrl: "https://images.unsplash.com/photo-1518005020951-eccb494ad742?auto=format&fit=crop&w=600&q=80",
    imageCaption: "A majestic cross glowing brightly against the morning sun and clouds, symbolizing Jesus Christ's message of unconditional love."
  },
  {
    key: "mohammad",
    name: "Prophet Mohammad",
    originalName: "محمد‎",
    religion: "islam",
    role: "The Messenger & Unifier",
    attributes: ["Tawhid (Monotheism)", "Justice", "Mercy", "Integrity"],
    scriptureRef: { bookKey: "quran", bookTitle: "The Holy Quran" },
    summary: "The final Prophet of Islam. Known prior to his calling as 'Al-Amin' (The Trustworthy), he received the Quranic revelations from Angel Gabriel and unified Arabia under the worship of the one single God, Allah, while establishing direct social justice.",
    detailedEthos: "Mohammad represents spiritual devotion integrated with civic and ethical responsibility. He was a champion of widows, orphans, and the poor, establishing systemic legal protections, freeing slaves, and teaching that all human beings are perfectly equal like the teeth of a comb, regardless of race or tribe.",
    story: "In his youth, long before his prophethood, the tribes of Mecca were rebuilding the Kaaba and fell into a fierce dispute over who would have the honor of placing the sacred Black Stone. A war was imminent. Mohammad proposed a beautiful solution: he spread his cloak on the ground, placed the stone in the center, and invited the leaders of all competing tribes to grasp the edges of the cloak and lift it together, teaching that shared honor and peace are better than tribal pride.",
    interfaithEcho: "Mohammad's systemic defense of the poor and call to absolute monotheism parallels the fiery social warnings of the Hebrew Prophets (like Isaiah and Amos) demanding that true worship must express itself through justice for the oppressed.",
    imageUrl: "https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=600&q=80",
    imageCaption: "Prismatic light casting beautiful shadows through classic arches, representing Prophet Mohammad's message of Monotheism and structural justice."
  },
  {
    key: "abraham",
    name: "Abraham",
    originalName: "אַבְרָהָם / إبراهيم",
    religion: "judaism",
    role: "The Father of Faith",
    attributes: ["Submission", "Hospitality", "Covenant", "Surrender"],
    scriptureRef: { bookKey: "quran", bookTitle: "The Holy Quran" },
    summary: "The shared patriarch of Judaism, Christianity, and Islam. He responded to the divine call to leave his ancestral home, demonstrated unmatched hospitality to passing strangers, and showed absolute willingness to surrender everything out of faith.",
    detailedEthos: "Abraham represents the archetype of perfect faith (Emunah / Islam)—the total surrender of personal logic and security to align with divine truth. He is also celebrated for his extreme warmth and hospitality, keeping his desert tent open on all four sides to welcome and feed travelers of all backgrounds without question.",
    story: "When three anonymous travelers appeared near his tent in the midday heat, Abraham did not ask their tribe, beliefs, or business. He immediately ran from his tent, bowed low, brought water to wash their feet, and ordered a magnificent feast of fresh bread and roasted calf. He stood by them under the trees, serving them personally. These travelers turned out to be celestial messengers of God, teaching that when we welcome strangers, we welcome the divine.",
    interfaithEcho: "Abraham's unconditional hospitality to passing strangers is the supreme scriptural standard for the Hindu code of 'Atithi Devo Bhava' (The Guest is God) and Buddhist hospitality, teaching that sharing food is a sacred, non-sectarian covenant.",
    imageUrl: "https://images.unsplash.com/photo-1507692049790-de58290a4334?auto=format&fit=crop&w=600&q=80",
    imageCaption: "A vast star-studded evening canopy over desert peaks, representing the covenant and the sacred promise granted to Abraham."
  },
  {
    key: "ravana",
    name: "Ravana",
    originalName: "रावण",
    religion: "history",
    role: "The Scholar-King of Lanka",
    attributes: ["Immense Devotion", "Intellect", "Veena Master", "Hubris"],
    scriptureRef: { bookKey: "ramayana", bookTitle: "Ramayana" },
    summary: "The formidable, ten-headed king of Lanka in the Ramayana. An incredibly powerful scholar, physician, master of the Veena, and a favorite devotee of Lord Shiva, whose towering ego and possessive desires ultimately led to his destruction.",
    detailedEthos: "Ravana represents the tragic complexity of magnificent human potential ruined by hubris (Ahamkara). He had ten heads representing his masterful command over the six shastras and four Vedas. Yet, his inability to control his senses and his proud delusion that he was superior to all beings show that intellectual power without ethical character is self-destructive.",
    story: "To show his intense devotion to Lord Shiva, Ravana attempted to lift Shiva's absolute mountain home, Mount Kailash. Shiva lightly pressed down the mountain with his toe, trapping Ravana's fingers. Instead of crying out in anger, Ravana seized his own tendons to construct string instruments and composed the beautiful, thunderous 'Shiva Tandava Stotra', singing ecstatic praises. Pleased by his unmatched dedication and musical genius, Shiva freed him and granted him the divine sword Chandrahas.",
    interfaithEcho: "Ravana's tragic trajectory of magnificent intellectual and spiritual starting height collapsing through pride is a direct mirror to Lucifer in Christian theology or Icarus in myth, serving as a warning that ego ruins the highest souls.",
    imageUrl: "https://images.unsplash.com/photo-1511192336575-5a79af67a629?auto=format&fit=crop&w=600&q=80",
    imageCaption: "A beautiful traditional Indian Veena instrument, celebrating Ravana's unmatched musical dedication and Shiva Tandava composition."
  },
  {
    key: "surya",
    name: "Lord Surya",
    originalName: "सूर्य",
    religion: "hinduism",
    role: "The Solar Illuminator",
    attributes: ["Light of Intellect", "Vitality", "Constancy", "Gayatri"],
    scriptureRef: { bookKey: "upanishads", bookTitle: "Principal Upanishads" },
    summary: "The Hindu sun god, revered as the absolute physical eye of the universe and the source of all life and energy. He rides across the sky in a golden chariot drawn by seven horses representing the seven colors of light and days of the week.",
    detailedEthos: "Surya represents the illuminating light of the intellect and the quality of selflessness. He shines equally on the saint and the sinner, giving his energy without expecting anything in return. In the sacred Gayatri Mantra, seekers pray not for physical wealth, but for Surya's solar light to stimulate and clear their inner minds.",
    story: "Surya's heat was so intense and blinding that his wife Sanjna found it impossible to stay near him. She created a shadow duplicate of herself named Chhaya to take her place and fled to perform penance. When Surya discovered this, he realized his blinding light was alienating his loved ones. He willingly allowed his form to be shaved and trimmed on a potter's wheel by Viswakarma, reducing his extreme blinding glare so that he could warm the earth gently without burning it.",
    interfaithEcho: "Surya as the source of intellectual light and daily life matches the solar patterns of Ra in ancient Egypt, Apollo in Greek scriptures, and Sun of Righteousness in Malachi, highlighting light as the universal physical emblem of truth.",
    imageUrl: "https://images.unsplash.com/photo-1518241353330-0f7941c2d9b5?auto=format&fit=crop&w=600&q=80",
    imageCaption: "Glorious sunburst rays cutting through clouds, representing Lord Surya's solar chariot of truth and life-giving energy."
  },
  {
    key: "chandra",
    name: "Lord Chandra",
    originalName: "चन्द्र",
    religion: "hinduism",
    role: "The Lunar Nourisher",
    attributes: ["Mind & Emotion", "Tranquility", "Soma (Nectar)", "Rhythm"],
    scriptureRef: { bookKey: "upanishads", bookTitle: "Principal Upanishads" },
    summary: "The Hindu moon god, representing the cooling, emotional aspects of the human mind, water, tides, and the vital herbal nectar known as Soma that nourishes all plant life on earth.",
    detailedEthos: "If Surya represents the burning light of the active intellect, Chandra represents the soothing, reflective light of the emotional mind (Manas). He teaches that life flows in cycles of waxing and waning—that times of darkness are natural, and of shadow are always followed by gradual fullness and return of light.",
    story: "Chandra married the twenty-seven daughters of Sage Daksha (representing the 27 lunar constellations). However, he favored only one wife, Rohini, neglecting the other twenty-six. Offended by this unfairness, Daksha cursed Chandra to waste away and lose his golden light. Distressed, Chandra prayed to Lord Shiva. Shiva, unable to completely lift Daksha's curse, modified it: Chandra would wane for fifteen days, but would then grow back to full brightness for fifteen days, wearing the crescent moon on Shiva's own locks.",
    interfaithEcho: "Chandra's cyclical waxing and waning mirrors the deep mystical path of the 'dark night of the soul' in Christian mysticism or the middle gates of Taoism, where retreat and empty stillness are seen as prerequisites for full rejuvenation.",
    imageUrl: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=600&q=80",
    imageCaption: "A beautiful crescent moon glowing softly, symbolizing Lord Chandra's soothing lunar energy."
  },
  {
    key: "israel",
    name: "Israel (Jacob)",
    originalName: "יַעֲקֹב",
    religion: "judaism",
    role: "He Who Strives with God",
    attributes: ["Struggle", "Persistence", "Vision", "Twelve Tribes"],
    scriptureRef: { bookKey: "bible_nt", bookTitle: "The Bible" },
    summary: "The Hebrew patriarch Jacob, who was given the name 'Israel' after wrestling with a mysterious celestial traveler all night, rising to become the father of the twelve tribes of Israel through deep endurance.",
    detailedEthos: "Israel represents the beauty of wrestling with spiritual truth and existential suffering. Faith in this tradition is not passive agreement; it is an intense, active relationship of wrestling with doubts, questions, and hardships, refusing to let go until a true blessing of understanding is won.",
    story: "On the eve of meeting his estranged brother Esau, whom he had wronged years prior, Jacob found himself completely alone in the dark by the River Jabbok. Suddenly, a mysterious celestial figure engaged him in an intense wrestling match that lasted until the break of dawn. As the sky began to light up, the figure struck Jacob's hip socket, putting it out of joint, and demanded to be released. Jacob gasped: 'I will not let you go unless you bless me!' Impressed by his endurance, the figure declared: 'Your name shall no longer be Jacob, but Israel, for you have striven with God and humans, and have prevailed.'",
    interfaithEcho: "Jacob's intense overnight struggle and refusal to surrender until winning a blessing is a beautiful mirror to the Buddha sitting under the Bodhi tree, wrestling with the demons of Mara, vowing not to rise until achieving absolute awakening.",
    imageUrl: "https://images.unsplash.com/photo-1510154222993-ee6141d184fc?auto=format&fit=crop&w=600&q=80",
    imageCaption: "A warm golden silhouette representing Jacob's intense overnight wrestling match with a divine messenger before receiving the name Israel."
  },
  {
    key: "buddha",
    name: "Gautama Buddha",
    originalName: "सिद्धार्थ गौतम",
    religion: "buddhism",
    role: "The Awakened One",
    attributes: ["Middle Path", "Compassion", "Mindfulness", "Nirvana"],
    scriptureRef: { bookKey: "dhammapada", bookTitle: "Dhammapada" },
    summary: "Siddhartha Gautama, the founder of Buddhism. Born a wealthy prince, he renounced his luxurious palace to seek a cure for human suffering, discovering the Middle Path and achieving absolute enlightenment under the Bodhi tree.",
    detailedEthos: "Gautama Buddha represents the path of pristine psychological observation, deep scientific self-control, and absolute compassion (Karuna). He rejected both extreme luxury and extreme self-mortification, teaching that the mind is best stilled through a gentle, balanced Middle Path of mindfulness and virtuous conduct.",
    story: "After sitting beneath the Bodhi tree, Siddhartha entered deep meditation, vowing that even if his flesh and bones should wither, he would not rise until he solved the root of human suffering. Mara, the lord of illusion and desire, unleashed terrifying armies of demons, storms of burning coals, and seductive apparitions to break his focus. Smiling with profound equanimity, Siddhartha simply touched his hand to the earth (Bhumisparsha), calling the earth to witness his lifetimes of selfless virtue. The illusions instantly vanished, and as the morning star rose, he awoke as the Buddha.",
    interfaithEcho: "The Buddha's absolute victory over the seductive illusions and terrors of Mara under the Bodhi tree directly mirrors Jesus' forty days of resisting the temptations in the wilderness, showing the universal battle over the ego.",
    imageUrl: "https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=600&q=80",
    imageCaption: "A serene hand-carved golden Buddha statue meditating deeply, representing total mindfulness and the cessation of suffering under the Bodhi Tree."
  },
  {
    key: "mahavira",
    name: "Mahavir Swami",
    originalName: "वर्धमान महावीर",
    religion: "jainism",
    role: "The 24th Tirthankara",
    attributes: ["Ahimsa", "Aparigraha (Non-possession)", "Anekantavada", "Asceticism"],
    scriptureRef: { bookKey: "tattvartha_sutra", bookTitle: "Tattvartha Sutra" },
    summary: "Vardhamana Mahavira, the twenty-fourth spiritual conqueror (Tirthankara) of Jainism. He revived and systemized the five great vows, centering absolute non-violence (Ahimsa) toward all living entities in the cosmos.",
    detailedEthos: "Mahavira represents the summit of human self-discipline, rigorous truth, and infinite compassion. He walked barefoot, owned absolutely nothing, and swept the path before him to avoid harming insects, demonstrating that spiritual freedom is won by releasing all material attachments and showing perfect harmlessness.",
    story: "During his twelve years of deep silent meditation, Mahavira endured extreme physical trials. Once, as he sat in deep meditation near a village, a shepherd mistook him for a criminal and drove sharp wooden thorns deep into Mahavira's ears. Mahavira experienced intense physical pain, yet he did not feel a single drop of anger or resentment toward the shepherd. He maintained perfect internal equanimity and prayed for the shepherd's soul, showing that absolute Ahimsa is a state of loving mental invulnerability.",
    interfaithEcho: "Mahavira's extreme tolerance of physical torture and forgiveness toward his abusers is a magnificent parallel to Jesus forgiving his crucifiers, showing that high spiritual masters meet violence purely with transformative, peaceful light.",
    imageUrl: "https://images.unsplash.com/photo-1501854140801-50d01698950b?auto=format&fit=crop&w=600&q=80",
    imageCaption: "Tranquil mountain valleys untouched by human touch, expressing Mahavira's non-violence (Ahimsa) toward all living entities."
  },
  {
    key: "alexander",
    name: "Alexander the Great",
    originalName: "Ἀλέξανδρος ὁ Μέγας",
    religion: "history",
    role: "The Sovereign Conqueror",
    attributes: ["Ambition", "Tactical Genius", "Cosmopolitan Vision", "Indomitability"],
    scriptureRef: { bookKey: "anabasis_alexander", bookTitle: "Anabasis of Alexander" },
    summary: "The legendary king of Macedon who forged one of the largest empires in history. Renowned for his undefeated military record and tactical audacity, he sought to reach the 'ends of the world and the Great Outer Sea'.",
    detailedEthos: "Alexander represented a synthesis of heroic Homeric ambition and philosophical curiosity. Guided by Aristotle in his youth, he was not merely a conqueror but an explorer of worlds, attempting to fuse East and West under a single empire. He possessed intense stamina, leading charges personally and displaying genuine reverence for foreign sages.",
    story: "After crossing the Indus, Alexander encountered the 'Gymnosophists'—naked Indian philosophers meditating under the sun. Baffled by their calm indifference to his grand conquering army, Alexander demanded to know who was stronger. One of the sages pointed to a dried hide placed on the ground; when he stepped on one edge, the other rose. The sage explained that a king who rules by force only shifts trouble from one corner to another. Intrigued and humbled, Alexander honored their supreme contentness, recognizing that the conquest of the mind is greater than any mortal throne.",
    interfaithEcho: "Alexander's meeting with the quiet gymnosophists highlights a beautiful universal archetype: the secular ruler of extreme worldly power bowing before the quiet ascetic master, mirroring King Janaka seeking Sage Yajnavalkya or King Nebuchadnezzar's encounters with Daniel.",
    imageUrl: "https://images.unsplash.com/photo-1599733589046-9b8308b5b50d?auto=format&fit=crop&w=600&q=80",
    imageCaption: "An antique Greek marble bust of King Alexander the Great of Macedon, capturing his fierce eyes and determined worldview."
  },
  {
    key: "shivaji",
    name: "Maharaja Shivaji",
    originalName: "छत्रपती शिवाजी महाराज",
    religion: "history",
    role: "Defender of Swarajya & Righteous Justice",
    attributes: ["Swarajya", "Strategic Audacity", "Chivalric Code", "Religious Freedom"],
    scriptureRef: { bookKey: "siva_chhatrapati", bookTitle: "Siva Chhatrapati (Sabhasad Bakhar)" },
    summary: "The legendary founder of the Maratha Empire. Shivaji revolutionized warfare with speed, geography, and hill forts, establishing a sovereign state ('Hindavi Swarajya') based on ethical governance, social justice, and remarkable religious equality.",
    detailedEthos: "Shivaji was the epitome of progress, strategic brilliance, and deep personal integrity. Unlike rulers of his era, he maintained a strict code of chivalry, forbidding the harassment of captured women, protecting civilian populations, and ensuring that mosques and religious copies of all faiths (including the Quran) were protected, demonstrating absolute ethical leadership.",
    story: "Trapped in the fortress of Agra by Emperor Aurangzeb under tight guard, Shivaji's prospects seemed hopeless. Feigning severe illness, he began sending massive baskets of sweetmeats and fruits to poor citizens and priests as a religious charity. This routine continued for weeks, making guards complacent. One afternoon, Shivaji and his young son Sambhaji climbed inside those very baskets and slipped past the imperial guards, making a legendary escape that revived the flame of free self-rule.",
    interfaithEcho: "Shivaji's unyielding struggle for the freedom of his land while maintaining highest respect for all world scriptures is a beautiful historical echo of the Covenant in Israel demanding liberation from unjust empires, or the Sikh code of Saint-Soldier protecting the weak of all faiths.",
    imageUrl: "https://images.unsplash.com/photo-1589308078059-be1415eab4c3?auto=format&fit=crop&w=600&q=80",
    imageCaption: "A majestic stone fort on high mountain peaks, reflecting Chhatrapati Shivaji's strategic audacity."
  },
  {
    key: "pratap",
    name: "Maharana Pratap",
    originalName: "महाराणा प्रताप",
    religion: "history",
    role: "The Unyielding Shield of Mewar",
    attributes: ["Self-Respect", "Unyielding Honor", "Forest Survival", "Loyalty"],
    scriptureRef: { bookKey: "mewar_annals_pratap", bookTitle: "Annals of Mewar (Maharana Pratap)" },
    summary: "The heroic Rajput king of Mewar who famously refused to bow to Mughal Emperor Akbar. Facing overwhelming forces, he retreated to the rocky Aravalli hills, living in caves to wage a fierce guerilla war for Mewar's independence.",
    detailedEthos: "Maharana Pratap is a supreme monument to self-respect, raw endurance, and absolute love for ancestral soil. Rather than trading his freedom for imperial luxury, he chose to live in extreme poverty, taking a fierce oath to sleep on grass beds and eat wild crop bread until Mewar was liberated, inspiring generations of defenders.",
    story: "During the desperate Battle of Haldighati, Pratap was severely wounded and surrounded by enemy forces. Seeing his master in danger, his magnificent warhorse, Chetak, surged forward through the fray. Despite losing one leg and suffering fatal wounds, Chetak carried Pratap across a wide mountain stream, placing him in safety before collapsing and dying in his master's arms. Pratap wept, immortalizing Chetak as the ultimate symbol of pristine animal loyalty and devotion.",
    interfaithEcho: "Pratap's willingness to inhabit caves and eat wild bread rather than surrender his integrity matches the ascetic models of Old Testament prophets (like Elijah) living in mountain clefts, or John the Baptist surviving in the Judean wilderness.",
    imageUrl: "https://images.unsplash.com/photo-1511192336575-5a79af67a629?auto=format&fit=crop&w=600&q=80",
    imageCaption: "A classic antique shield and sword armor layout, honoring Maharana Pratap's unyielding military honor and Mewar defense."
  },
  {
    key: "julius_caesar",
    name: "Julius Caesar",
    originalName: "Gaius Iulius Caesar",
    religion: "history",
    role: "The Audacious Visionary & Consul",
    attributes: ["Clementia", "Oratory", "Decisiveness", "Imperial Majesty"],
    scriptureRef: { bookKey: "commentarii_bello_gallico", bookTitle: "Commentaries on the Gallic War" },
    summary: "The brilliant Roman general, statesman, and orator who transformed the Roman Republic into the soaring Roman Empire. Famous for his lightning-fast movements, strategic rhetoric, and famous clementia (mercy toward defeated foes).",
    detailedEthos: "Caesar represents absolute decisiveness and unparalleled confidence. Beyond his tactical genius, he practiced 'Clementia'—frequently pardoning his bitterest political rivals rather than executing them (though this ultimately led to his tragic betrayal). He was a master of psychological warfare and administrative reform.",
    story: "In 49 BC, standing at the banks of the tiny river Rubicon, which marked the sacred boundary of Rome, Caesar faced an existential crossroad. Crossing with an army would ignite a civil war. He stood in silent thought. Knowing that retreat meant political ruin and crossing meant irreversible struggle, he smiled and declared: 'Alea iacta est' (The die is cast). He plunged his horse into the current, teaching that some boundaries can only be transcended through decisive, total conviction.",
    interfaithEcho: "Caesar's dramatic crossing of the Rubicon to fulfill an imperial destiny matches the archetypal crossings of other scriptural leaders facing deep waters of no return, such as Joshua crossing the Jordan or Moses dividing the Red Sea to forge a nation.",
    imageUrl: "https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=600&q=80",
    imageCaption: "Ancient Roman ruins and white pillars, symbolizing Gaius Julius Caesar's epic crossings and leadership."
  },
  {
    key: "gilgamesh",
    name: "King Gilgamesh",
    originalName: "𒄑𒂆𒈦",
    religion: "history",
    role: "The Seeker of Immortality",
    attributes: ["Indomitable Strength", "Tragic Sorrow", "Enduring Brotherhood", "Wisdom"],
    scriptureRef: { bookKey: "epic_gilgamesh", bookTitle: "The Epic of Gilgamesh" },
    summary: "The legendary priest-king of Uruk, two-thirds divine and one-third human. After ruling with tyrannical power, his life was transformed by his deep brotherhood with Enkidu, whose tragic death sent him on an epic saga to seek the secret of eternal life.",
    detailedEthos: "Gilgamesh represents the eternal human struggle against mortality, existential despair, and the transformation of raw pride into humble wisdom. Initially self-centered, his deep grief for his companion leads him to explore the physical and metaphysical ends of the earth, eventually discovering that true immortality is found not in avoiding physical death, but in the enduring monuments and peaceful legacies build for one's people.",
    story: "After crossing the waters of death, Gilgamesh sought the sage Utnapishtim, who challenged him to defeat sleep if he wished to defeat death. Gilgamesh sat down, but weary from his travels, instantly fell asleep, sleeping for seven days. Upon waking, he realized his mortality. Utnapishtim then gifted him a youth-renewing flower from the ocean floor. While Gilgamesh bathed, a serpent stole the flower, eating it and shedding its skin. Returning empty-handed to his home of Uruk, Gilgamesh gazed upon its massive walls with clear eyes, finally achieving peace by dedicating himself to his kingdom.",
    interfaithEcho: "Gilgamesh's painful journey across deep oceans and dry deserts in search of the tree/flower of life parallels the Biblical Garden of Eden sequence where humans are barred from the Tree of Life, and the constant search across traditions for a source of ultimate spiritual renewal.",
    imageUrl: "https://images.unsplash.com/photo-1608988220025-a74ef43d463e?auto=format&fit=crop&w=600&q=80",
    imageCaption: "The massive ancient brick structures and carvings of Uruk, symbolizing the monumental brick walls built by King Gilgamesh."
  },
  {
    key: "achilles",
    name: "Achilles",
    originalName: "Ἀχιλλεύς",
    religion: "history",
    role: "The Peerless Champion of Wrath & Glory",
    attributes: ["Heroic Wrath", "Superhuman Martial Skill", "Fated Choice", "Sovereign Pride"],
    scriptureRef: { bookKey: "homers_iliad", bookTitle: "The Iliad" },
    summary: "The greatest Greek warrior of the Trojan War, son of the sea-nymph Thetis. Renowned for his near-invulnerability, fiery pride, and devastating rage, his fated choice between a short, glorious life and a long, quiet one sits at the heart of classical epic literature.",
    detailedEthos: "Achilles represents the tension between mortal transience and the pursuit of eternal glory (kleos). He is an intensely emotional character, moved by absolute pride and loyalty to those he loves. His near-godlike physical strength is contrasted directly by his emotional vulnerability and his tragic awareness of his own fated early death under the walls of Troy.",
    story: "Blinded by fury at the death of his beloved companion Patroclus, Achilles slew Hector, the Trojan prince, and dragged his body behind his chariot for twelve days in an act of desecration. That night, King Priam of Troy secretly slipped into the Greek camp, kissed Achilles' hands, and begged for his son's corpse. Looking at the old king, Achilles wept, remembering his own father, and recognized their shared suffering and mortality. He lifted Priam up and returned Hector's body, revealing a deep, transcending core of basic human empathy.",
    interfaithEcho: "Achilles' sudden, beautiful breakthrough of grief-driven empathy for his enemy Priam mirrors the epic moments in the Mahabharata where warriors recognize the shared human soul on both sides of a cataclysmic battle, demonstrating that deep sorrow can wipe away political and national enmity.",
    imageUrl: "https://images.unsplash.com/photo-1531572753726-0fd02dd4245c?auto=format&fit=crop&w=600&q=80",
    imageCaption: "An ancient classical Greek bronze armour detail, representing the peerless warrior Achilles of Trojan War fame."
  },
  {
    key: "sun_wukong",
    name: "Sun Wukong (The Monkey King)",
    originalName: "孫悟空",
    religion: "buddhism",
    role: "The Great Sage Equal to Heaven",
    attributes: ["Playful Trickster", "Incredible Magic", "Unyielding Power", "Spiritual Enlightenment"],
    scriptureRef: { bookKey: "journey_west", bookTitle: "Journey to the West" },
    summary: "Born from a mythical stone egg, Sun Wukong attained godlike martial skills, 72 transformations, and absolute immortality. After rebelling against heaven, he was trapped under a mountain for 500 years until he reformed to protect the monk Tang Sanzang on his sacred pilgrimage.",
    detailedEthos: "Sun Wukong represents the untamed nature of the human mind—mischievous, clever, incredibly capable, yet prone to extreme pride and chaos. His spiritual journey is a vivid allegory for refining this 'monkey mind' through devotional discipline, loyalty, and selfless service, eventually earning him the title of 'Victorious Fighting Buddha'.",
    story: "During their pilgrimage, a terrifying demon disguised herself three times as a helpless peasant girl to trick the moral, gullible monk Tang Sanzang. Each time, Wukong's golden eyes saw through the illusion and he struck her down to save his master. Mistaking Wukong's actions for bloodthirsty violence, Sanzang chanted the painful 'Band-Tightening Spell' around Wukong's head, causing him agony, and cast him away. Despite his hurt and exile, when another demon captured Sanzang, Wukong returned without hesitation, defeating the threat and saving his master, proving his unswerving loyalty.",
    interfaithEcho: "Wukong's transformation from a selfish, chaotic rebel into a dedicated protector of sacred text matches the universal archetype of the wild, untamable force being converted into a highly disciplined knight of light, such as Saint Paul on the road to Damascus.",
    imageUrl: "https://images.unsplash.com/photo-1508672019048-805c876b67e2?auto=format&fit=crop&w=600&q=80",
    imageCaption: "The misty, jagged, and heavily forested peaks of Mount Huaguo, the legendary celestial birthplace and home of the Monkey King."
  },
  {
    key: "ragnar",
    name: "Ragnar Lothbrok",
    originalName: "Ragnarr Loðbrók",
    religion: "mythology",
    role: "Legendary Norse King & Viking Leader",
    attributes: ["Valour", "Daring", "Strategy", "Viking Code"],
    scriptureRef: { bookKey: "saga_ragnar_lothbrok", bookTitle: "The Saga of Ragnar Lothbrok" },
    summary: "The celebrated Norse chieftain and king from legendary sagas. Wielding fierce courage and incredible tactical cunning, he raided Anglo-Saxon England and West Frankia, and faced death in a pit of vipers with a joyous shout.",
    detailedEthos: "Ragnar embodies the raw, unbending warrior spirit of the Viking Age. While he is represented as a fierce fighter, he is also a brilliant strategist who uses psychological terror and physical adaptability (such as his famous tar-coated protective trousers). He faces his fated death in Northumbria without a shiver of fear, welcoming Valhalla and his sons' vengeance.",
    story: "Captured by King Ælla of Northumbria and cast into a deep, dark pit crawling with venomous vipers, Ragnar Lothbrok refused to beg for mercy. As the snakes bit his flesh, he sang his custom death-song, famously declaring: 'The piglets would grunt if they knew how the old boar suffered!' He laughed in the face of death, boasting that Odin had prepared a golden horn for him in Valhalla, and that his sons would sail across the seas to exact a blood-curdling revenge.",
    interfaithEcho: "Ragnar's laughter and unshakeable courage when facing torture in the viper pit mirrors the martyrdom accounts of early Christian saints or Sikh warriors smiling in the face of execution, proving that a deep devotion to one's spiritual fated home can completely transcend physical pain.",
    imageUrl: "https://images.unsplash.com/photo-1506458959157-965f8c07b9bb?auto=format&fit=crop&w=600&q=80",
    imageCaption: "A Viking dragon-ship navigating cold Northern waters, representing the legendary Norse king and explorer Ragnar Lothbrok."
  }
];
